name: Run tests for SAM project
on:
  push:
    paths:
      - 'sam/**'
      - '.github/workflows/sam.yml'
      - '.github/start_sam_locally.sh'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: XXXXXXX
#          aws-secret-access-key: XXXXXXXXXX
#          aws-region: us-east-2
      # Build inside Docker containers
      - run: cd sam/sam-app && sam build
      - run: ./.github/start_sam_locally.sh
      - run: cd sam/sam-app && python3 -m pip install -r tests/requirements.txt
      - run: cd sam/sam-app && python3 -m unittest discover -s tests/unit -p 'test_*.py'
      - run: cd sam/sam-app && python3 -m unittest discover -s tests/integration -p 'test_*.py'
        env:
          AWS_SAM_TEST_HOST:  "localhost:3000"